{{ config(materialized="table",schema = 'TRANSFORMING') }}
select 
PRODUCTID, 
PRODUCTNAME, 
SUPPLIERID, 
CATEGORYID, 
QUANTITYPERUNIT, 
UNITCOST, 
UNITPRICE, 
UNITSINSTOCK, 
UNITSONORDER,
CASE WHEN (UNITSINSTOCK-UNITSONORDER)> 0 THEN 'YES' ELSE 'NO' END AS   PRODUCTAVAILABILITY,
UNITPRICE-UNITCOST AS PROFIT
from {{ ref('products') }}